### ISSUE TITLE
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.

### ISSUE THREAD

**Issue by sarajbosna2012** [meowtec/Imagine#57]
### Version
latest version

### Operating system (version and arch)
eg: Windows 10 x64

### Describe the bug
npm i
npm start

(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
and electron does not open. it shows electron as running in windows tasks.

**Comment by meowtec** [comment]
The warning is caused by `electron-updater` and `electron-log` and it does't matter.

Could you show more information? There should be more logs like `app launch xxx` `url loaded`. (You can mask some sensitive information.)

What about the [binary](https://github.com/meowtec/Imagine/releases)? What about `npm run dev`?

**Comment by sarajbosna2012** [comment]
i fixed it by updating electron-log to later version.
